name: rsvp
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^4.0.0
  screenshot: ^1.3.0
  share: ^2.0.4
  path_provider: ^2.0.11
  slide_to_act: ^2.0.2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/assets/cover-image-01.jpg
    - lib/assets/cover-image-02.jpg
    - lib/assets/cover-image-03.jpg
    - lib/assets/cover-image-04.jpg
    - lib/assets/profile-image-01.jpg
    - lib/assets/profile-image-02.jpg
    - lib/assets/profile-image-03.jpg
    - lib/assets/splash-screen.png

  fonts:
    - family: Poppins
      fonts:
        - asset: lib/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: lib/fonts/Poppins-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: lib/fonts/Poppins-Light.ttf
          weight: 300
        - asset: lib/fonts/Poppins-LightItalic.ttf
          weight: 300
          style: italic
        - asset: lib/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: lib/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: lib/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: lib/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: lib/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: lib/fonts/Poppins-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: lib/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: lib/fonts/Poppins-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: lib/fonts/Poppins-Black.ttf
          weight: 900
        - asset: lib/fonts/Poppins-BlackItalic.ttf
          weight: 900
          style: italic

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
